### ISSUE TITLE
Redis cache invalidation on entity update

### ISSUE THREAD

**Issue by de00x** [strapi-community/strapi-plugin-redis#26] opened 2024-08-09 09:13 UTC
Hey everyone.
Could you please help me out? I'm facing an issue with Redis caching.
When one entity in the Strapi collection is modified, Redis removes the entire cache for that entity, and everything gets reset.
P.S. Maybe it's because we're using the REST API?
I'll leave the libraries we're using on the project:
"strapi-plugin-redis": "1.0.1",
"strapi-plugin-rest-cache": "4.2.8",
"strapi-provider-rest-cache-redis": "4.2.8",

**Comment by derrickmehaffy** [comment] 2024-08-09 13:26
Duplicate of https://github.com/strapi-community/strapi-plugin-rest-cache/issues/94

**Closed** 2024-08-09 13:27 UTC
