### ISSUE TITLE
Strapi Loads forever on v1.1.0

### ISSUE THREAD

**Issue by mrtrom** [strapi-community/strapi-plugin-redis#23] opened 2024-03-13 20:08 UTC
**Description:**
I am in the process of updating my Strapi dependencies and I got a bit stuck when trying to update this one.
When trying to run `yarn develop` or `yarn start` (after building) it just gets stuck in `Loading Strapi`.

Investigating a little I saw that in the latest release the file `server/bootstrap.js` was moved to `server/register.js`. Now, if I change this again to be `server/bootstrap.js` everything works correctly. Wondering if this change was intended or if something is wrong in my setup 🤔 

PD: Happy to create a PR with this change!

**Steps to reproduce:**

- Install version 1.1.0 of `strapi-plugin-redis`
- Run `yarn develop`

**Expected behavior:**
The app loads correctly

**Actual behavior:**
The service gets stuck in `Loading Stripe`.
![CleanShot 2024-03-13 at 15 04 08](https://github.com/strapi-community/strapi-plugin-redis/assets/2824053/65e8aec9-b029-4731-bc47-effc4bfab369)

**Environment:**
Strapi version: 4.20.5 (but it happens on previous versions as well)
Node.js version: 20.11.0
Yarn version: 1.22.19

**Comment by derrickmehaffy** [comment] 2024-03-19 04:01
I moved this to register to fix problems with other plugins loaded before mine but indeed the issue is probably in REST cache ATM and a release for that is pending.

**Comment by derrickmehaffy** [comment] 2024-07-22 16:50
Closing as I think this is resolved in REST Cache but if not respond back and I can reopen

**Closed by derrickmehaffy** 2024-07-22 16:50 UTC

**Comment by pinkasey** [comment] 2025-05-21 10:03
I'm also facing this issue.
Strapi 4.25.20
strapi-plugin-redis: 1.1.0
strapi-plugin-rest-cache: 4.2.9 *

* strapi-plugin-rest-cache - I've forked from it to add functionality, based on 4.2.9. I'm pretty sure I didn't change the infra to affect this issue, so let's say I have 4.2.9

Is there an issue in strapi-plugin-rest-cache that fixes it?
a version that does?
If anyone posted a link here, it would serve following people who come across it.
